### ISSUE TITLE
Logging from a mobile client

### ISSUE THREAD

**Issue by clayellis** [amzn/smoke-aws-support#9]
I'm evaluating Swift packages that support logging to CloudWatch via [swift-log](https://github.com/apple/swift-log). I've taken a brief look at this one and I'm wondering whether the maintainers would say that this package could be used from an iOS app to post logs to CloudWatch? Or is it not meant to be used that way?

It doesn't appear to actually support sending the logs to CloudWatch. Rather, it just writes out to `TextOutputStream`. Is that true, or am I missing something?

**Comment by knovichikhin** [comment]
This package does not send logs directly to CloudWatch. This package is used within AWS container and assumes that container has CW agent running.
